---
# TODO: other_sites need more complex data struct with no_www_redirect.


- name: Set site name without test suffix for default host.
  set_fact:
    apache_vhost_site_name: "{{ site_name }}"
  when: site_name == '000-default'

- name: Add .local suffix to apache_vhost_site_name if needed.
  set_fact:
    apache_vhost_site_name: "{{ site_name ~ local_test_environment|default('') }}"
  when: site_name != '000-default'

- name: Install package apache2
  apt:
    pkg=apache2
    state=present

- name: Create site directory if it does not exist.
  file:
    state=directory
    path={{ apache_vhost_webroot }}
    owner=root
    group=root
    mode=0755
  when: apache_vhost_webroot is defined and apache_vhost_no_create_webroot is not defined

- name: Create robots.txt directory
  file:
    path={{ apache_vhost_robots_txt_dir }}
    state=directory
    owner=root
    group=root
    mode=0755

- name: Copy a robots.txt
  template:
    src={{roles_path}}/{{ apache_vhost_robots_txt }}
    dest={{ apache_vhost_robots_txt_dir }}/{{ apache_vhost_robots_txt_filename }}
    owner=root
    group=root
    mode=0644

- name: Set other_vhosts_access_log to use syslog.
  template:
    src: other_vhosts_access_log.j2
    dest: /etc/apache2/conf.d/other-vhosts-access-log
    owner: root
    group: root
    mode: 0644
  when: apache_vhost_log_to_syslog == true

- name: Apache config for site
  template:
    src={{ apache_vhost_template_path }}/{{ vhost_template }}
    dest=/etc/apache2/sites-available/{{apache_vhost_site_name}}
    owner=root
    group=root
    mode=0644
  register: apache_site_config

- name: Check the site config exists.
  stat: path=/etc/apache2/sites-available/{{apache_vhost_site_name}}
  register: site_config


- name: Enable site in apache config
  file:
    src=/etc/apache2/sites-available/{{ apache_vhost_site_name }}
    dest=/etc/apache2/sites-enabled/{{ apache_vhost_site_name }}
    owner=root
    group=root
    state=link
  when: site_config.stat.exists
  notify:
    - reload apache

- name: Install snippet for avahi config if in test environment.
  template: src=avahi_aliases.j2 dest={{AVAHI_ALIASES_CONFIG_DIR}}/{{apache_vhost_site_name}}
  when: local_test_environment is defined and apache_vhost_avahi_alias
  notify:
    - restart avahi-alias
